# Generated by Django 4.2 on 2024-10-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_PORTO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='initial_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
