# Generated by Django 4.2 on 2024-10-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_PORTO', '0002_remove_asset_created_at_remove_asset_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='asset_name',
        ),
    ]
