# Generated by Django 4.2 on 2024-10-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_PORTO', '0003_rename_name_asset_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
