# Generated by Django 4.2 on 2024-10-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_PORTO', '0005_remove_transaction_amount_alter_transaction_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=15),
            preserve_default=False,
        ),
    ]
