# Generated by Django 4.2 on 2024-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_PORTO', '0006_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('purchase', 'Pembelian'), ('sale', 'Penjualan')], max_length=50),
        ),
    ]
