# Generated by Django 4.2 on 2024-10-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_PORTO', '0007_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
